version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data


  frontend:
    image: 58708150aa/frontend
    environment:
    - BACKEND=http://localhost:8081
    ports:
      - "4200:80"
    depends_on:
      - backend
      - keycloak


  backend:
    image: 58708150aa/backends
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=12345678
      - PORT=8081
      - FRONTEND=http://localhost:4200
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=app-micro
    ports:
      - "8081:8081"
    depends_on:
      - neo4j
      - keycloak


  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/12345678
    ports:
      - "7687:7687"
    volumes:
      - neo4j_data:/data    
      - neo4j_logs:/logs    
      - neo4j_import:/import 
      - neo4j_plugins:/plugins 

  keycloak:
    image: 58708150aa/custom-keycloak:latest
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

